# Create all directories and files at once
mkdir -p src/components/{shared,auth,dashboard,audits,questions,templates,reports,settings,profile} src/contexts && \
echo 'import React from "react"; export default function LoadingScreen() { return <div className="flex items-center justify-center min-h-screen"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div></div>; }' > src/components/shared/LoadingScreen.js && \
echo 'import React from "react"; class ErrorBoundary extends React.Component { state = { hasError: false }; static getDerivedStateFromError() { return { hasError: true }; } render() { return this.state.hasError ? <div>Error occurred</div> : this.props.children; }} export default ErrorBoundary;' > src/components/shared/ErrorBoundary.js && \
for comp in NotFound; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/shared/$comp.js; done && \
for comp in Login PrivateRoute; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/auth/$comp.js; done && \
for comp in Dashboard; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/dashboard/$comp.js; done && \
for comp in AuditList AuditDetail AuditForm; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/audits/$comp.js; done && \
for comp in QuestionBank; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/questions/$comp.js; done && \
for comp in Templates; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/templates/$comp.js; done && \
for comp in Reports; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/reports/$comp.js; done && \
for comp in Settings; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/settings/$comp.js; done && \
for comp in Profile; do echo "import React from 'react'; export default function $comp() { return <div>$comp Component</div>; }" > src/components/profile/$comp.js; done && \
for ctx in AuthContext DataContext ThemeContext NotificationContext; do echo "import React, { createContext, useContext } from 'react'; const $ctx = createContext(); export function ${ctx%.Context}Provider({ children }) { return <$ctx.Provider value={{}}>{children}</$ctx.Provider>; } export function use${ctx%.Context}() { return useContext($ctx); }" > src/contexts/$ctx.js; done