import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Supported languages
export const SUPPORTED_LANGUAGES = {
  en: { code: 'en', name: 'English', flag: '🇬🇧', speechCode: 'en-US' },
  de: { code: 'de', name: 'Deutsch', flag: '🇩🇪', speechCode: 'de-DE' },
  es: { code: 'es', name: 'Español', flag: '🇪🇸', speechCode: 'es-ES' },
  fil: { code: 'fil', name: 'Filipino', flag: '🇵🇭', speechCode: 'fil-PH' },
  fr: { code: 'fr', name: 'Français', flag: '🇫🇷', speechCode: 'fr-FR' },
  it: { code: 'it', name: 'Italiano', flag: '🇮🇹', speechCode: 'it-IT' },
  pl: { code: 'pl', name: 'Polski', flag: '🇵🇱', speechCode: 'pl-PL' },
  pt: { code: 'pt', name: 'Português', flag: '🇵🇹', speechCode: 'pt-PT' },
  ro: { code: 'ro', name: 'Română', flag: '🇷🇴', speechCode: 'ro-RO' },
  sr: { code: 'sr', name: 'Srpski', flag: '🇷🇸', speechCode: 'sr-RS' },
  tr: { code: 'tr', name: 'Türkçe', flag: '🇹🇷', speechCode: 'tr-TR' },
};

// Translations for all UI elements
const translations = {
  en: {
    // Greetings
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    there: 'there',

    // Dashboard
    dashboardSubtitle: "Here's what's happening with your audits today.",
    totalAudits: 'Total Audits',
    completed: 'Completed',
    openActions: 'Open Actions',
    avgScore: 'Avg Score',
    vsLastWeek: 'vs last week',
    improvement: 'improvement',
    weeklyOverview: 'Weekly Overview',
    auditsAndScores: 'Audits and scores over time',
    thisWeek: 'This Week',
    lastWeek: 'Last Week',
    thisMonth: 'This Month',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    recentAudits: 'Recent Audits',
    noAuditsYet: 'No audits yet',
    getStartedAudit: 'Get started by creating your first audit',
    createAudit: 'Create Audit',
    quickStartTemplates: 'Quick Start Templates',
    browseAll: 'Browse All',
    viewReports: 'View Reports',
    newAudit: 'New Audit',
    min: 'min',

    // Navigation
    dashboard: 'Dashboard',
    audits: 'Audits',
    templates: 'Templates',
    actions: 'Actions',
    analytics: 'Analytics',
    team: 'Team',
    settings: 'Settings',

    // Common Actions
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    add: 'Add',
    remove: 'Remove',
    back: 'Back',
    next: 'Next',
    done: 'Done',

    // Templates Page
    templatesTitle: 'Templates',
    templatesSubtitle: 'Manage your audit inspection templates',
    searchTemplates: 'Search templates...',
    newTemplate: 'New Template',
    createNewTemplate: 'Create New Template',
    startAudit: 'Start Audit',
    noTemplatesFound: 'No templates found',
    noTemplatesMatch: 'No templates match your search.',
    createFirstTemplate: 'Create your first template to get started.',
    deleteTemplate: 'Delete Template',
    deleteTemplateConfirm: 'Are you sure you want to delete this template?',
    templateWillBeRemoved: 'will be permanently removed.',
    editTemplate: 'Edit Template',
    templateName: 'Template Name',
    templateDescription: 'Description',
    templateCategory: 'Category',
    estimatedTime: 'Estimated Time',
    sections: 'sections',
    questions: 'Questions',
    addSection: 'Add Section',
    addQuestion: 'Add Question',
    sectionTitle: 'Section Title',
    questionText: 'Question Text',
    questionType: 'Question Type',
    required: 'Required',
    critical: 'Critical',
    saveChanges: 'Save Changes',

    // AI Generation
    smartGeneration: 'Smart Generation',
    describeOrUpload: 'Describe your audit or upload a paper form',
    textToTemplate: 'Text to Template',
    imageToTemplate: 'Image to Template',
    describeYourTemplate: 'Describe your audit template',
    category: 'Category',
    examplePrompts: 'Example prompts:',
    uploadPaperForm: 'Upload paper form image',
    imageUploadHint: 'JPG, PNG, or PDF - Max 10MB',
    imageUploaded: 'Image uploaded - Ready to extract template',
    uploadHint: 'Upload a photo of a paper checklist, audit form, or inspection sheet. The structure and questions will be extracted automatically.',
    importJSON: 'Import JSON',
    generateTemplate: 'Generate Template',
    generating: 'Generating...',
    generatedTemplatePreview: 'Generated Template Preview',
    regenerate: 'Regenerate',
    saveTemplate: 'Save Template',

    // Import Results
    importResults: 'Import Results',
    total: 'Total',
    imported: 'Imported',
    skipped: 'Skipped',
    issuesFound: 'Issues Found',
    successfullyImported: 'Successfully imported',
    templateS: 'template(s)',

    // Audits Page
    auditsTitle: 'Audits',
    auditsSubtitle: 'View and manage your safety inspections',
    allStatuses: 'All Statuses',
    draft: 'Draft',
    inProgress: 'In Progress',

    // Audit Detail
    auditDetail: 'Audit Detail',
    auditSummary: 'Audit Summary',
    score: 'Score',
    status: 'Status',
    location: 'Location',
    date: 'Date',
    completedAt: 'Completed At',
    createdBy: 'Created By',
    signedBy: 'Signed By',

    // Question Item
    safe: 'Safe',
    risk: 'Risk',
    na: 'N/A',
    describeTheIssue: 'Describe the issue',
    describeTheProblem: 'Describe the problem...',
    enhanceNoteHint: 'Click the wand icon to enhance your note with AI',
    photos: 'Photos',
    safetyAnalysis: 'Safety Analysis',
    hazardDetected: 'Hazard Detected',
    severity: 'Severity',
    noHazardsDetected: 'No Hazards Detected',
    recommendation: 'Recommendation',
    useAsAction: 'Use as Action',
    complianceStatus: 'Compliance Status',
    confidence: 'Confidence',
    recording: 'Recording...',
    processing: 'Processing...',
    transcript: 'Transcript',
    stopAndProcess: 'Stop & Process',
    smartVoiceAssistant: 'Smart Voice Assistant',
    aiAnalyzedVoice: 'AI analyzed your voice note',
    tapToApply: 'Tap to apply',
    extractedDetails: 'Extracted Details',
    keyObservations: 'Key Observations',
    recommendedAction: 'Recommended Action',
    addPhoto: 'Add Photo',
    analyze: 'Analyze',
    analyzing: 'Analyzing...',
    createAction: 'Create Action',
    newAction: 'New Action',
    autoSuggest: 'Auto-Suggest',
    suggesting: 'Suggesting...',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    ownerTeam: 'Owner Team',
    none: 'None',
    description: 'Description',
    describeAction: 'Describe what action needs to be taken...',
    getRegulationsInfo: 'Get ASchG regulations info',
    translateQuestion: 'Translate question to local language',

    // Actions Page
    actionsTitle: 'Action Items',
    actionsSubtitle: 'Track and manage corrective actions',
    allPriorities: 'All Priorities',
    open: 'Open',
    closed: 'Closed',
    dueDate: 'Due Date',
    assignee: 'Assignee',
    owner: 'Owner',

    // Analytics
    analyticsTitle: 'Analytics',
    analyticsSubtitle: 'Insights and trends from your audits',

    // Team
    teamTitle: 'Team',
    teamSubtitle: 'Manage your team members',

    // Settings
    settingsTitle: 'Settings',
    settingsSubtitle: 'Configure your preferences',
    language: 'Language',
    selectLanguage: 'Select Language',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',

    // Policy Chatbot
    policyAssistant: 'Policy Assistant',
    policySubtitle: 'Austrian ASchG & OSHA Guidelines',
    policyGreeting: "Hello! I'm the AuditHub Policy Assistant. I can help you with questions about Austrian workplace safety regulations (ASchG), OSHA standards, and general safety compliance. What would you like to know?",
    typeMessage: 'Type your message...',
    send: 'Send',
    sources: 'Sources',
    relatedTopics: 'Related Topics',

    // Translation feature
    translatedQuestion: 'Translated Question',
    stepsToCheck: 'Steps to Check',
    translateToLocal: 'Translate to Local Language',
    translating: 'Translating...',
    originalQuestion: 'Original Question',

    // Misc
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    tapToCapture: 'Tap to capture photo',
    enterYourNotes: 'Enter your notes...',
  },

  de: {
    // Greetings
    goodMorning: 'Guten Morgen',
    goodAfternoon: 'Guten Tag',
    goodEvening: 'Guten Abend',
    there: 'da',

    // Dashboard
    dashboardSubtitle: 'Hier ist, was heute mit Ihren Audits passiert.',
    totalAudits: 'Gesamt Audits',
    completed: 'Abgeschlossen',
    openActions: 'Offene Maßnahmen',
    avgScore: 'Ø Punktzahl',
    vsLastWeek: 'vs letzte Woche',
    improvement: 'Verbesserung',
    weeklyOverview: 'Wochenübersicht',
    auditsAndScores: 'Audits und Punktzahlen im Zeitverlauf',
    thisWeek: 'Diese Woche',
    lastWeek: 'Letzte Woche',
    thisMonth: 'Dieser Monat',
    recentActivity: 'Letzte Aktivitäten',
    viewAll: 'Alle anzeigen',
    recentAudits: 'Letzte Audits',
    noAuditsYet: 'Noch keine Audits',
    getStartedAudit: 'Erstellen Sie Ihr erstes Audit, um zu beginnen',
    createAudit: 'Audit erstellen',
    quickStartTemplates: 'Schnellstart-Vorlagen',
    browseAll: 'Alle durchsuchen',
    viewReports: 'Berichte anzeigen',
    newAudit: 'Neues Audit',
    min: 'Min',

    // Navigation
    dashboard: 'Dashboard',
    audits: 'Audits',
    templates: 'Vorlagen',
    actions: 'Maßnahmen',
    analytics: 'Analysen',
    team: 'Team',
    settings: 'Einstellungen',

    // Common Actions
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    confirm: 'Bestätigen',
    search: 'Suchen',
    filter: 'Filtern',
    export: 'Exportieren',
    import: 'Importieren',
    add: 'Hinzufügen',
    remove: 'Entfernen',
    back: 'Zurück',
    next: 'Weiter',
    done: 'Fertig',

    // Templates Page
    templatesTitle: 'Vorlagen',
    templatesSubtitle: 'Verwalten Sie Ihre Audit-Inspektionsvorlagen',
    searchTemplates: 'Vorlagen suchen...',
    newTemplate: 'Neue Vorlage',
    createNewTemplate: 'Neue Vorlage erstellen',
    startAudit: 'Audit starten',
    noTemplatesFound: 'Keine Vorlagen gefunden',
    noTemplatesMatch: 'Keine Vorlagen entsprechen Ihrer Suche.',
    createFirstTemplate: 'Erstellen Sie Ihre erste Vorlage, um zu beginnen.',
    deleteTemplate: 'Vorlage löschen',
    deleteTemplateConfirm: 'Sind Sie sicher, dass Sie diese Vorlage löschen möchten?',
    templateWillBeRemoved: 'wird dauerhaft entfernt.',
    editTemplate: 'Vorlage bearbeiten',
    templateName: 'Vorlagenname',
    templateDescription: 'Beschreibung',
    templateCategory: 'Kategorie',
    estimatedTime: 'Geschätzte Zeit',
    sections: 'Abschnitte',
    questions: 'Fragen',
    addSection: 'Abschnitt hinzufügen',
    addQuestion: 'Frage hinzufügen',
    sectionTitle: 'Abschnittstitel',
    questionText: 'Fragentext',
    questionType: 'Fragentyp',
    required: 'Erforderlich',
    critical: 'Kritisch',
    saveChanges: 'Änderungen speichern',

    // AI Generation
    smartGeneration: 'Intelligente Generierung',
    describeOrUpload: 'Beschreiben Sie Ihr Audit oder laden Sie ein Papierformular hoch',
    textToTemplate: 'Text zu Vorlage',
    imageToTemplate: 'Bild zu Vorlage',
    describeYourTemplate: 'Beschreiben Sie Ihre Audit-Vorlage',
    category: 'Kategorie',
    examplePrompts: 'Beispiel-Eingaben:',
    uploadPaperForm: 'Papierformular-Bild hochladen',
    imageUploadHint: 'JPG, PNG oder PDF - Max 10MB',
    imageUploaded: 'Bild hochgeladen - Bereit zur Extraktion',
    uploadHint: 'Laden Sie ein Foto einer Papier-Checkliste, eines Audit-Formulars oder Inspektionsbogens hoch. Die Struktur und Fragen werden automatisch extrahiert.',
    importJSON: 'JSON importieren',
    generateTemplate: 'Vorlage generieren',
    generating: 'Generiere...',
    generatedTemplatePreview: 'Generierte Vorlagenvorschau',
    regenerate: 'Neu generieren',
    saveTemplate: 'Vorlage speichern',

    // Import Results
    importResults: 'Import-Ergebnisse',
    total: 'Gesamt',
    imported: 'Importiert',
    skipped: 'Übersprungen',
    issuesFound: 'Probleme gefunden',
    successfullyImported: 'Erfolgreich importiert',
    templateS: 'Vorlage(n)',

    // Audits Page
    auditsTitle: 'Audits',
    auditsSubtitle: 'Sicherheitsinspektionen anzeigen und verwalten',
    allStatuses: 'Alle Status',
    draft: 'Entwurf',
    inProgress: 'In Bearbeitung',

    // Audit Detail
    auditDetail: 'Audit-Details',
    auditSummary: 'Audit-Zusammenfassung',
    score: 'Punktzahl',
    status: 'Status',
    location: 'Standort',
    date: 'Datum',
    completedAt: 'Abgeschlossen am',
    createdBy: 'Erstellt von',
    signedBy: 'Unterzeichnet von',

    // Question Item
    safe: 'Sicher',
    risk: 'Risiko',
    na: 'N/A',
    describeTheIssue: 'Beschreiben Sie das Problem',
    describeTheProblem: 'Beschreiben Sie das Problem...',
    enhanceNoteHint: 'Klicken Sie auf das Zauberstab-Symbol, um Ihre Notiz mit KI zu verbessern',
    photos: 'Fotos',
    safetyAnalysis: 'Sicherheitsanalyse',
    hazardDetected: 'Gefahr erkannt',
    severity: 'Schweregrad',
    noHazardsDetected: 'Keine Gefahren erkannt',
    recommendation: 'Empfehlung',
    useAsAction: 'Als Maßnahme verwenden',
    complianceStatus: 'Compliance-Status',
    confidence: 'Konfidenz',
    recording: 'Aufnahme...',
    processing: 'Verarbeite...',
    transcript: 'Transkript',
    stopAndProcess: 'Stoppen & Verarbeiten',
    smartVoiceAssistant: 'Intelligenter Sprachassistent',
    aiAnalyzedVoice: 'KI hat Ihre Sprachnotiz analysiert',
    tapToApply: 'Tippen zum Anwenden',
    extractedDetails: 'Extrahierte Details',
    keyObservations: 'Wichtige Beobachtungen',
    recommendedAction: 'Empfohlene Maßnahme',
    addPhoto: 'Foto hinzufügen',
    analyze: 'Analysieren',
    analyzing: 'Analysiere...',
    createAction: 'Maßnahme erstellen',
    newAction: 'Neue Maßnahme',
    autoSuggest: 'Auto-Vorschlag',
    suggesting: 'Schlage vor...',
    priority: 'Priorität',
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
    ownerTeam: 'Verantwortliches Team',
    none: 'Keines',
    description: 'Beschreibung',
    describeAction: 'Beschreiben Sie, welche Maßnahme ergriffen werden muss...',
    getRegulationsInfo: 'ASchG-Vorschriften abrufen',
    translateQuestion: 'Frage in lokale Sprache übersetzen',

    // Actions Page
    actionsTitle: 'Maßnahmen',
    actionsSubtitle: 'Korrekturmaßnahmen verfolgen und verwalten',
    allPriorities: 'Alle Prioritäten',
    open: 'Offen',
    closed: 'Geschlossen',
    dueDate: 'Fälligkeitsdatum',
    assignee: 'Zugewiesen an',
    owner: 'Verantwortlicher',

    // Analytics
    analyticsTitle: 'Analysen',
    analyticsSubtitle: 'Einblicke und Trends aus Ihren Audits',

    // Team
    teamTitle: 'Team',
    teamSubtitle: 'Verwalten Sie Ihre Teammitglieder',

    // Settings
    settingsTitle: 'Einstellungen',
    settingsSubtitle: 'Konfigurieren Sie Ihre Präferenzen',
    language: 'Sprache',
    selectLanguage: 'Sprache auswählen',
    darkMode: 'Dunkelmodus',
    notifications: 'Benachrichtigungen',

    // Policy Chatbot
    policyAssistant: 'Richtlinien-Assistent',
    policySubtitle: 'Österreichische ASchG & OSHA Richtlinien',
    policyGreeting: 'Hallo! Ich bin der AuditHub Richtlinien-Assistent. Ich kann Ihnen bei Fragen zu österreichischen Arbeitsschutzvorschriften (ASchG), OSHA-Standards und allgemeiner Sicherheits-Compliance helfen. Was möchten Sie wissen?',
    typeMessage: 'Nachricht eingeben...',
    send: 'Senden',
    sources: 'Quellen',
    relatedTopics: 'Verwandte Themen',

    // Translation feature
    translatedQuestion: 'Übersetzte Frage',
    stepsToCheck: 'Prüfschritte',
    translateToLocal: 'In lokale Sprache übersetzen',
    translating: 'Übersetze...',
    originalQuestion: 'Originalfrage',

    // Misc
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    warning: 'Warnung',
    info: 'Info',
    tapToCapture: 'Tippen, um ein Foto aufzunehmen',
    enterYourNotes: 'Geben Sie Ihre Notizen ein...',
  },

  es: {
    // Greetings
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    there: 'ahí',
    dashboardSubtitle: 'Esto es lo que está pasando con tus auditorías hoy.',
    totalAudits: 'Total Auditorías',
    completed: 'Completadas',
    openActions: 'Acciones Abiertas',
    avgScore: 'Puntuación Media',
    vsLastWeek: 'vs semana pasada',
    improvement: 'mejora',
    weeklyOverview: 'Resumen Semanal',
    auditsAndScores: 'Auditorías y puntuaciones a lo largo del tiempo',
    thisWeek: 'Esta Semana',
    lastWeek: 'Semana Pasada',
    thisMonth: 'Este Mes',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    recentAudits: 'Auditorías Recientes',
    noAuditsYet: 'Aún no hay auditorías',
    getStartedAudit: 'Comienza creando tu primera auditoría',
    createAudit: 'Crear Auditoría',
    quickStartTemplates: 'Plantillas de Inicio Rápido',
    browseAll: 'Ver Todas',
    viewReports: 'Ver Informes',
    newAudit: 'Nueva Auditoría',
    min: 'min',
    dashboard: 'Panel',
    audits: 'Auditorías',
    templates: 'Plantillas',
    actions: 'Acciones',
    analytics: 'Análisis',
    team: 'Equipo',
    settings: 'Configuración',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    close: 'Cerrar',
    confirm: 'Confirmar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    add: 'Añadir',
    remove: 'Eliminar',
    back: 'Atrás',
    next: 'Siguiente',
    done: 'Hecho',
    templatesTitle: 'Plantillas',
    templatesSubtitle: 'Gestiona tus plantillas de inspección de auditoría',
    searchTemplates: 'Buscar plantillas...',
    newTemplate: 'Nueva Plantilla',
    createNewTemplate: 'Crear Nueva Plantilla',
    startAudit: 'Iniciar Auditoría',
    noTemplatesFound: 'No se encontraron plantillas',
    noTemplatesMatch: 'Ninguna plantilla coincide con tu búsqueda.',
    createFirstTemplate: 'Crea tu primera plantilla para comenzar.',
    deleteTemplate: 'Eliminar Plantilla',
    deleteTemplateConfirm: '¿Estás seguro de que quieres eliminar esta plantilla?',
    templateWillBeRemoved: 'será eliminada permanentemente.',
    editTemplate: 'Editar Plantilla',
    templateName: 'Nombre de Plantilla',
    templateDescription: 'Descripción',
    templateCategory: 'Categoría',
    estimatedTime: 'Tiempo Estimado',
    sections: 'secciones',
    questions: 'Preguntas',
    addSection: 'Añadir Sección',
    addQuestion: 'Añadir Pregunta',
    sectionTitle: 'Título de Sección',
    questionText: 'Texto de Pregunta',
    questionType: 'Tipo de Pregunta',
    required: 'Requerido',
    critical: 'Crítico',
    saveChanges: 'Guardar Cambios',
    smartGeneration: 'Generación Inteligente',
    describeOrUpload: 'Describe tu auditoría o sube un formulario en papel',
    textToTemplate: 'Texto a Plantilla',
    imageToTemplate: 'Imagen a Plantilla',
    describeYourTemplate: 'Describe tu plantilla de auditoría',
    category: 'Categoría',
    examplePrompts: 'Ejemplos:',
    uploadPaperForm: 'Subir imagen de formulario',
    imageUploadHint: 'JPG, PNG o PDF - Máx 10MB',
    imageUploaded: 'Imagen subida - Lista para extraer',
    uploadHint: 'Sube una foto de una lista de verificación, formulario de auditoría u hoja de inspección. La estructura y preguntas se extraerán automáticamente.',
    importJSON: 'Importar JSON',
    generateTemplate: 'Generar Plantilla',
    generating: 'Generando...',
    generatedTemplatePreview: 'Vista Previa de Plantilla Generada',
    regenerate: 'Regenerar',
    saveTemplate: 'Guardar Plantilla',
    importResults: 'Resultados de Importación',
    total: 'Total',
    imported: 'Importadas',
    skipped: 'Omitidas',
    issuesFound: 'Problemas Encontrados',
    successfullyImported: 'Importadas exitosamente',
    templateS: 'plantilla(s)',
    auditsTitle: 'Auditorías',
    auditsSubtitle: 'Ver y gestionar tus inspecciones de seguridad',
    allStatuses: 'Todos los Estados',
    draft: 'Borrador',
    inProgress: 'En Progreso',
    auditDetail: 'Detalle de Auditoría',
    auditSummary: 'Resumen de Auditoría',
    score: 'Puntuación',
    status: 'Estado',
    location: 'Ubicación',
    date: 'Fecha',
    completedAt: 'Completado el',
    createdBy: 'Creado por',
    signedBy: 'Firmado por',
    safe: 'Seguro',
    risk: 'Riesgo',
    na: 'N/A',
    describeTheIssue: 'Describe el problema',
    describeTheProblem: 'Describe el problema...',
    enhanceNoteHint: 'Haz clic en el icono de varita para mejorar tu nota con IA',
    photos: 'Fotos',
    safetyAnalysis: 'Análisis de Seguridad',
    hazardDetected: 'Peligro Detectado',
    severity: 'Gravedad',
    noHazardsDetected: 'Sin Peligros Detectados',
    recommendation: 'Recomendación',
    useAsAction: 'Usar como Acción',
    complianceStatus: 'Estado de Cumplimiento',
    confidence: 'Confianza',
    recording: 'Grabando...',
    processing: 'Procesando...',
    transcript: 'Transcripción',
    stopAndProcess: 'Detener y Procesar',
    smartVoiceAssistant: 'Asistente de Voz Inteligente',
    aiAnalyzedVoice: 'La IA analizó tu nota de voz',
    tapToApply: 'Toca para aplicar',
    extractedDetails: 'Detalles Extraídos',
    keyObservations: 'Observaciones Clave',
    recommendedAction: 'Acción Recomendada',
    addPhoto: 'Añadir Foto',
    analyze: 'Analizar',
    analyzing: 'Analizando...',
    createAction: 'Crear Acción',
    newAction: 'Nueva Acción',
    autoSuggest: 'Auto-Sugerir',
    suggesting: 'Sugiriendo...',
    priority: 'Prioridad',
    low: 'Baja',
    medium: 'Media',
    high: 'Alta',
    ownerTeam: 'Equipo Responsable',
    none: 'Ninguno',
    description: 'Descripción',
    describeAction: 'Describe qué acción se debe tomar...',
    getRegulationsInfo: 'Obtener info de regulaciones ASchG',
    translateQuestion: 'Traducir pregunta al idioma local',
    actionsTitle: 'Elementos de Acción',
    actionsSubtitle: 'Seguimiento y gestión de acciones correctivas',
    allPriorities: 'Todas las Prioridades',
    open: 'Abierto',
    closed: 'Cerrado',
    dueDate: 'Fecha de Vencimiento',
    assignee: 'Asignado a',
    owner: 'Responsable',
    analyticsTitle: 'Análisis',
    analyticsSubtitle: 'Información y tendencias de tus auditorías',
    teamTitle: 'Equipo',
    teamSubtitle: 'Gestiona los miembros de tu equipo',
    settingsTitle: 'Configuración',
    settingsSubtitle: 'Configura tus preferencias',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    darkMode: 'Modo Oscuro',
    notifications: 'Notificaciones',
    policyAssistant: 'Asistente de Políticas',
    policySubtitle: 'Directrices ASchG austriaco y OSHA',
    policyGreeting: '¡Hola! Soy el Asistente de Políticas de AuditHub. Puedo ayudarte con preguntas sobre regulaciones de seguridad laboral austriacas (ASchG), estándares OSHA y cumplimiento de seguridad general. ¿Qué te gustaría saber?',
    typeMessage: 'Escribe tu mensaje...',
    send: 'Enviar',
    sources: 'Fuentes',
    relatedTopics: 'Temas Relacionados',
    translatedQuestion: 'Pregunta Traducida',
    stepsToCheck: 'Pasos a Verificar',
    translateToLocal: 'Traducir al Idioma Local',
    translating: 'Traduciendo...',
    originalQuestion: 'Pregunta Original',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    warning: 'Advertencia',
    info: 'Info',
    tapToCapture: 'Toca para capturar foto',
    enterYourNotes: 'Ingresa tus notas...',
  },

  fr: {
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    there: 'là',
    dashboardSubtitle: "Voici ce qui se passe avec vos audits aujourd'hui.",
    totalAudits: 'Total Audits',
    completed: 'Terminés',
    openActions: 'Actions Ouvertes',
    avgScore: 'Score Moyen',
    vsLastWeek: 'vs semaine dernière',
    improvement: 'amélioration',
    weeklyOverview: 'Aperçu Hebdomadaire',
    auditsAndScores: 'Audits et scores au fil du temps',
    thisWeek: 'Cette Semaine',
    lastWeek: 'Semaine Dernière',
    thisMonth: 'Ce Mois',
    recentActivity: 'Activité Récente',
    viewAll: 'Voir Tout',
    recentAudits: 'Audits Récents',
    noAuditsYet: 'Pas encore d\'audits',
    getStartedAudit: 'Commencez par créer votre premier audit',
    createAudit: 'Créer un Audit',
    quickStartTemplates: 'Modèles de Démarrage Rapide',
    browseAll: 'Parcourir Tout',
    viewReports: 'Voir les Rapports',
    newAudit: 'Nouvel Audit',
    min: 'min',
    dashboard: 'Tableau de Bord',
    audits: 'Audits',
    templates: 'Modèles',
    actions: 'Actions',
    analytics: 'Analyses',
    team: 'Équipe',
    settings: 'Paramètres',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    confirm: 'Confirmer',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    add: 'Ajouter',
    remove: 'Supprimer',
    back: 'Retour',
    next: 'Suivant',
    done: 'Terminé',
    templatesTitle: 'Modèles',
    templatesSubtitle: 'Gérez vos modèles d\'inspection d\'audit',
    searchTemplates: 'Rechercher des modèles...',
    newTemplate: 'Nouveau Modèle',
    createNewTemplate: 'Créer un Nouveau Modèle',
    startAudit: 'Démarrer l\'Audit',
    noTemplatesFound: 'Aucun modèle trouvé',
    noTemplatesMatch: 'Aucun modèle ne correspond à votre recherche.',
    createFirstTemplate: 'Créez votre premier modèle pour commencer.',
    deleteTemplate: 'Supprimer le Modèle',
    deleteTemplateConfirm: 'Êtes-vous sûr de vouloir supprimer ce modèle?',
    templateWillBeRemoved: 'sera définitivement supprimé.',
    editTemplate: 'Modifier le Modèle',
    templateName: 'Nom du Modèle',
    templateDescription: 'Description',
    templateCategory: 'Catégorie',
    estimatedTime: 'Temps Estimé',
    sections: 'sections',
    questions: 'Questions',
    addSection: 'Ajouter une Section',
    addQuestion: 'Ajouter une Question',
    sectionTitle: 'Titre de Section',
    questionText: 'Texte de Question',
    questionType: 'Type de Question',
    required: 'Requis',
    critical: 'Critique',
    saveChanges: 'Enregistrer les Modifications',
    smartGeneration: 'Génération Intelligente',
    describeOrUpload: 'Décrivez votre audit ou téléchargez un formulaire papier',
    textToTemplate: 'Texte vers Modèle',
    imageToTemplate: 'Image vers Modèle',
    describeYourTemplate: 'Décrivez votre modèle d\'audit',
    category: 'Catégorie',
    examplePrompts: 'Exemples:',
    uploadPaperForm: 'Télécharger l\'image du formulaire',
    imageUploadHint: 'JPG, PNG ou PDF - Max 10Mo',
    imageUploaded: 'Image téléchargée - Prêt à extraire',
    uploadHint: 'Téléchargez une photo d\'une liste de contrôle, d\'un formulaire d\'audit ou d\'une fiche d\'inspection. La structure et les questions seront extraites automatiquement.',
    importJSON: 'Importer JSON',
    generateTemplate: 'Générer le Modèle',
    generating: 'Génération...',
    generatedTemplatePreview: 'Aperçu du Modèle Généré',
    regenerate: 'Régénérer',
    saveTemplate: 'Enregistrer le Modèle',
    importResults: 'Résultats d\'Importation',
    total: 'Total',
    imported: 'Importés',
    skipped: 'Ignorés',
    issuesFound: 'Problèmes Trouvés',
    successfullyImported: 'Importés avec succès',
    templateS: 'modèle(s)',
    safe: 'Sûr',
    risk: 'Risque',
    na: 'N/A',
    describeTheIssue: 'Décrivez le problème',
    describeTheProblem: 'Décrivez le problème...',
    photos: 'Photos',
    safetyAnalysis: 'Analyse de Sécurité',
    hazardDetected: 'Danger Détecté',
    noHazardsDetected: 'Aucun Danger Détecté',
    recommendation: 'Recommandation',
    recording: 'Enregistrement...',
    processing: 'Traitement...',
    addPhoto: 'Ajouter Photo',
    analyze: 'Analyser',
    analyzing: 'Analyse...',
    createAction: 'Créer Action',
    priority: 'Priorité',
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    description: 'Description',
    language: 'Langue',
    selectLanguage: 'Sélectionner la Langue',
    darkMode: 'Mode Sombre',
    policyAssistant: 'Assistant Politique',
    translateQuestion: 'Traduire la question',
    translatedQuestion: 'Question Traduite',
    stepsToCheck: 'Étapes à Vérifier',
    translating: 'Traduction...',
    originalQuestion: 'Question Originale',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
  },

  it: {
    goodMorning: 'Buongiorno',
    goodAfternoon: 'Buon pomeriggio',
    goodEvening: 'Buonasera',
    there: 'lì',
    dashboardSubtitle: 'Ecco cosa sta succedendo con i tuoi audit oggi.',
    totalAudits: 'Totale Audit',
    completed: 'Completati',
    openActions: 'Azioni Aperte',
    avgScore: 'Punteggio Medio',
    dashboard: 'Pannello',
    audits: 'Audit',
    templates: 'Modelli',
    actions: 'Azioni',
    settings: 'Impostazioni',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    search: 'Cerca',
    language: 'Lingua',
    selectLanguage: 'Seleziona Lingua',
    safe: 'Sicuro',
    risk: 'Rischio',
    na: 'N/A',
    addPhoto: 'Aggiungi Foto',
    analyze: 'Analizza',
    priority: 'Priorità',
    low: 'Bassa',
    medium: 'Media',
    high: 'Alta',
    translateQuestion: 'Traduci domanda',
    translatedQuestion: 'Domanda Tradotta',
    stepsToCheck: 'Passi da Verificare',
    translating: 'Traduzione...',
    loading: 'Caricamento...',
  },

  pl: {
    goodMorning: 'Dzień dobry',
    goodAfternoon: 'Dzień dobry',
    goodEvening: 'Dobry wieczór',
    there: 'tam',
    dashboardSubtitle: 'Oto co dzieje się z Twoimi audytami dzisiaj.',
    totalAudits: 'Wszystkie Audyty',
    completed: 'Ukończone',
    openActions: 'Otwarte Działania',
    avgScore: 'Średni Wynik',
    dashboard: 'Panel',
    audits: 'Audyty',
    templates: 'Szablony',
    actions: 'Działania',
    settings: 'Ustawienia',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    search: 'Szukaj',
    language: 'Język',
    selectLanguage: 'Wybierz Język',
    safe: 'Bezpieczny',
    risk: 'Ryzyko',
    na: 'N/D',
    addPhoto: 'Dodaj Zdjęcie',
    analyze: 'Analizuj',
    priority: 'Priorytet',
    low: 'Niski',
    medium: 'Średni',
    high: 'Wysoki',
    translateQuestion: 'Przetłumacz pytanie',
    translatedQuestion: 'Przetłumaczone Pytanie',
    stepsToCheck: 'Kroki do Sprawdzenia',
    translating: 'Tłumaczenie...',
    loading: 'Ładowanie...',
  },

  pt: {
    goodMorning: 'Bom dia',
    goodAfternoon: 'Boa tarde',
    goodEvening: 'Boa noite',
    there: 'aí',
    dashboardSubtitle: 'Aqui está o que está acontecendo com suas auditorias hoje.',
    totalAudits: 'Total de Auditorias',
    completed: 'Concluídas',
    openActions: 'Ações Abertas',
    avgScore: 'Pontuação Média',
    dashboard: 'Painel',
    audits: 'Auditorias',
    templates: 'Modelos',
    actions: 'Ações',
    settings: 'Configurações',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    search: 'Pesquisar',
    language: 'Idioma',
    selectLanguage: 'Selecionar Idioma',
    safe: 'Seguro',
    risk: 'Risco',
    na: 'N/A',
    addPhoto: 'Adicionar Foto',
    analyze: 'Analisar',
    priority: 'Prioridade',
    low: 'Baixa',
    medium: 'Média',
    high: 'Alta',
    translateQuestion: 'Traduzir pergunta',
    translatedQuestion: 'Pergunta Traduzida',
    stepsToCheck: 'Passos a Verificar',
    translating: 'Traduzindo...',
    loading: 'Carregando...',
  },

  ro: {
    goodMorning: 'Bună dimineața',
    goodAfternoon: 'Bună ziua',
    goodEvening: 'Bună seara',
    there: 'acolo',
    dashboardSubtitle: 'Iată ce se întâmplă cu auditurile tale astăzi.',
    totalAudits: 'Total Audituri',
    completed: 'Finalizate',
    openActions: 'Acțiuni Deschise',
    avgScore: 'Scor Mediu',
    dashboard: 'Panou',
    audits: 'Audituri',
    templates: 'Șabloane',
    actions: 'Acțiuni',
    settings: 'Setări',
    save: 'Salvează',
    cancel: 'Anulează',
    delete: 'Șterge',
    edit: 'Editează',
    search: 'Caută',
    language: 'Limbă',
    selectLanguage: 'Selectează Limba',
    safe: 'Sigur',
    risk: 'Risc',
    na: 'N/A',
    addPhoto: 'Adaugă Foto',
    analyze: 'Analizează',
    priority: 'Prioritate',
    low: 'Scăzută',
    medium: 'Medie',
    high: 'Ridicată',
    translateQuestion: 'Traduce întrebarea',
    translatedQuestion: 'Întrebare Tradusă',
    stepsToCheck: 'Pași de Verificat',
    translating: 'Se traduce...',
    loading: 'Se încarcă...',
  },

  tr: {
    goodMorning: 'Günaydın',
    goodAfternoon: 'İyi günler',
    goodEvening: 'İyi akşamlar',
    there: 'orada',
    dashboardSubtitle: 'Bugün denetimlerinizde neler oluyor.',
    totalAudits: 'Toplam Denetim',
    completed: 'Tamamlanan',
    openActions: 'Açık Eylemler',
    avgScore: 'Ort. Puan',
    dashboard: 'Panel',
    audits: 'Denetimler',
    templates: 'Şablonlar',
    actions: 'Eylemler',
    settings: 'Ayarlar',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    search: 'Ara',
    language: 'Dil',
    selectLanguage: 'Dil Seçin',
    safe: 'Güvenli',
    risk: 'Risk',
    na: 'N/A',
    addPhoto: 'Fotoğraf Ekle',
    analyze: 'Analiz Et',
    priority: 'Öncelik',
    low: 'Düşük',
    medium: 'Orta',
    high: 'Yüksek',
    translateQuestion: 'Soruyu çevir',
    translatedQuestion: 'Çevrilmiş Soru',
    stepsToCheck: 'Kontrol Adımları',
    translating: 'Çevriliyor...',
    loading: 'Yükleniyor...',
  },

  // Serbian translations
  sr: {
    // Greetings
    goodMorning: 'Добро јутро',
    goodAfternoon: 'Добар дан',
    goodEvening: 'Добро вече',
    there: 'ту',

    // Dashboard
    dashboardSubtitle: 'Ево шта се данас дешава са вашим ревизијама.',
    totalAudits: 'Укупно ревизија',
    completed: 'Завршено',
    openActions: 'Отворене акције',
    avgScore: 'Просечан резултат',
    recentAudits: 'Недавне ревизије',
    noAuditsYet: 'Још нема ревизија',
    createAudit: 'Креирај ревизију',
    newAudit: 'Нова ревизија',

    // Navigation
    dashboard: 'Контролна табла',
    audits: 'Ревизије',
    templates: 'Шаблони',
    actions: 'Акције',
    analytics: 'Аналитика',
    team: 'Тим',
    settings: 'Подешавања',

    // Common Actions
    save: 'Сачувај',
    cancel: 'Откажи',
    delete: 'Обриши',
    edit: 'Измени',
    close: 'Затвори',
    search: 'Претрага',

    // Settings
    language: 'Језик',
    selectLanguage: 'Изаберите језик',

    // Question Item
    safe: 'Безбедно',
    risk: 'Ризик',
    na: 'Н/П',
    addPhoto: 'Додај фотографију',
    analyze: 'Анализирај',

    // Priority
    priority: 'Приоритет',
    low: 'Низак',
    medium: 'Средњи',
    high: 'Висок',

    // Translation feature
    translateQuestion: 'Преведи питање',
    translatedQuestion: 'Преведено питање',
    stepsToCheck: 'Кораци за проверу',
    translating: 'Превођење...',
    loading: 'Учитавање...',
  },

  // Filipino translations
  fil: {
    // Greetings
    goodMorning: 'Magandang umaga',
    goodAfternoon: 'Magandang hapon',
    goodEvening: 'Magandang gabi',
    there: 'dyan',

    // Dashboard
    dashboardSubtitle: 'Ito ang nangyayari sa iyong mga audit ngayon.',
    totalAudits: 'Kabuuang Audit',
    completed: 'Nakumpleto',
    openActions: 'Bukas na Aksyon',
    avgScore: 'Ave. Puntos',
    recentAudits: 'Kamakailang Audit',
    noAuditsYet: 'Wala pang audit',
    createAudit: 'Gumawa ng Audit',
    newAudit: 'Bagong Audit',

    // Navigation
    dashboard: 'Dashboard',
    audits: 'Mga Audit',
    templates: 'Mga Template',
    actions: 'Mga Aksyon',
    analytics: 'Analytics',
    team: 'Koponan',
    settings: 'Mga Setting',

    // Common Actions
    save: 'I-save',
    cancel: 'Kanselahin',
    delete: 'Tanggalin',
    edit: 'I-edit',
    close: 'Isara',
    search: 'Maghanap',

    // Settings
    language: 'Wika',
    selectLanguage: 'Pumili ng Wika',

    // Question Item
    safe: 'Ligtas',
    risk: 'Panganib',
    na: 'N/A',
    addPhoto: 'Magdagdag ng Larawan',
    analyze: 'Suriin',

    // Priority
    priority: 'Priyoridad',
    low: 'Mababa',
    medium: 'Katamtaman',
    high: 'Mataas',

    // Translation feature
    translateQuestion: 'Isalin ang tanong',
    translatedQuestion: 'Naisaling Tanong',
    stepsToCheck: 'Mga Hakbang sa Pagsuri',
    translating: 'Nagsasalin...',
    loading: 'Naglo-load...',
  },
};

// Fill in missing translations with English fallback
Object.keys(SUPPORTED_LANGUAGES).forEach(lang => {
  if (lang !== 'en' && translations[lang]) {
    Object.keys(translations.en).forEach(key => {
      if (!translations[lang][key]) {
        translations[lang][key] = translations.en[key];
      }
    });
  }
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved && SUPPORTED_LANGUAGES[saved]) {
        return saved;
      }
      // Try to detect browser language
      const browserLang = navigator.language.split('-')[0];
      if (SUPPORTED_LANGUAGES[browserLang]) {
        return browserLang;
      }
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function
  const t = (key) => {
    return translations[language]?.[key] || translations.en?.[key] || key;
  };

  // Get current language info
  const currentLanguage = SUPPORTED_LANGUAGES[language];

  // Get greeting based on time of day
  const getGreeting = () => {
    const hour = new Date().getHours();
    if (hour < 12) return t('goodMorning');
    if (hour < 18) return t('goodAfternoon');
    return t('goodEvening');
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      currentLanguage,
      getGreeting,
      supportedLanguages: SUPPORTED_LANGUAGES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
